var locations = [
  {
    "RunClubName": "Boogie Down Bronx Runners",
    "Borough": "Bronx",
    "Address": "785 Pelham Pkwy N, Bronx, NY 10467, USA",
    "Website": "https://www.instagram.com/boogiedownbronxrunners/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.8581815,
    "longitude": -73.8641542
  },
  {
    "RunClubName": "Bronx Burners",
    "Borough": "Bronx",
    "Address": "216 Fort Washington Ave, New York, NY 10032, USA",
    "Website": "https://www.instagram.com/bronxburnersrc/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.8424312,
    "longitude": -73.9420153
  },
  {
    "RunClubName": "Bronx Femme Run",
    "Borough": "Bronx",
    "Address": "East 161st St. &, Macombs Dam Bridge, Bronx, NY 10451, USA",
    "Website": "https://www.instagram.com/bronxfemmerun/",
    "DayType": "Weekday",
    "Days": "Friday",
    "Times": "6:30 PM",
    "Distance": "Run 3.5M, Run/Walk 3.2M, Walk 2.5M",
    "latitude": 40.8279782,
    "longitude": -73.9289895
  },
  {
    "RunClubName": "Bronx Nomads",
    "Borough": "Bronx",
    "Address": "Holt Place and, Reservoir Oval E, Bronx, NY 10467, USA",
    "Website": "https://www.instagram.com/bronxnomads/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "6:30 PM",
    "Distance": "Community Run",
    "latitude": 40.8776269,
    "longitude": -73.8763876
  },
  {
    "RunClubName": "Bronx Nomads",
    "Borough": "Bronx",
    "Address": "2335 Reservoir Oval E, Bronx, NY 10467, USA",
    "Website": "https://www.instagram.com/bronxnomads/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:30 PM",
    "Distance": "Track",
    "latitude": 40.8760936,
    "longitude": -73.8780948
  },
  {
    "RunClubName": "Bronx Rockets",
    "Borough": "Bronx",
    "Address": "Rev. T. Wendell Foster Park, 1055 Jerome Ave, Bronx, NY 10452, USA",
    "Website": "https://www.instagram.com/bronx_rockets/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "8:00 AM",
    "Distance": "Run/Walk",
    "latitude": 40.8327854,
    "longitude": -73.9243201
  },
  {
    "RunClubName": "Bronx Sole",
    "Borough": "Bronx",
    "Address": "Franz Sigel Park, Walton Ave & Gerard Ave., Grand Concourse bet. E. 151 St., E. 153 St. and, E 158th St, Bronx, NY 10451, USA",
    "Website": "https://www.instagram.com/bronxsole/",
    "DayType": "Both",
    "Days": "Tuesday, Saturday",
    "Times": "6:15 PM, 10:00 AM",
    "Distance": "2.5M walk, 3M run/walk, 4M run",
    "latitude": 40.823285,
    "longitude": -73.92554319999999
  },
  {
    "RunClubName": "BX Endurance Runners",
    "Borough": "Bronx",
    "Address": "East 161st St. &, Macombs Dam Bridge, Bronx, NY 10451, USA",
    "Website": "https://www.instagram.com/bxendurancerunners/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "Paused",
    "Distance": "",
    "latitude": 40.8279782,
    "longitude": -73.9289895
  },
  {
    "RunClubName": "BX Endurance Runners",
    "Borough": "Bronx",
    "Address": "Joyce Kilmer Park, 955 Walton Ave, Bronx, NY 10452, USA",
    "Website": "https://www.instagram.com/bxendurancerunners/",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "8:00 AM",
    "Distance": "",
    "latitude": 40.8286949,
    "longitude": -73.9224792
  },
  {
    "RunClubName": "Great Hill Track Club",
    "Borough": "Bronx",
    "Address": "Van Cortlandt Park - 242 St, Bronx, NY 10471, USA",
    "Website": "https://www.instagram.com/greathilltc/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 PM",
    "Distance": "Speed/Tempo Alternate Weeks",
    "latitude": 40.8899894,
    "longitude": -73.8980578
  },
  {
    "RunClubName": "Mile Stylers",
    "Borough": "Bronx",
    "Address": "940 Garrison Ave, Bronx, NY 10474, USA",
    "Website": "https://www.instagram.com/milestylers/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 PM",
    "Distance": "Run 3.1M/Walk 2M",
    "latitude": 40.8182557,
    "longitude": -73.8901861
  },
  {
    "RunClubName": "Startline Runners",
    "Borough": "Bronx",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.eventbrite.com/o/startline-runners-31156520587",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "6:00 PM",
    "Distance": "",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "Startline Runners",
    "Borough": "Bronx",
    "Address": "Tortoise & Hare Statue, 6087C Broadway, Bronx, NY 10471, USA",
    "Website": "https://www.eventbrite.com/o/startline-runners-31156520587",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "8:00 AM",
    "Distance": "",
    "latitude": 40.8939928,
    "longitude": -73.89633560000001
  },
  {
    "RunClubName": "The Leftovers Run Club",
    "Borough": "Bronx",
    "Address": "East 161st St. &, Macombs Dam Bridge, Bronx, NY 10451, USA",
    "Website": "https://www.instagram.com/theleftoversrun/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:30 PM",
    "Distance": "Speed",
    "latitude": 40.8279782,
    "longitude": -73.9289895
  },
  {
    "RunClubName": "Van Cortlandt Track Club",
    "Borough": "Bronx",
    "Address": "Van Cortlandt Park - 242 St, Bronx, NY 10471, USA",
    "Website": "https://www.instagram.com/vancortlandttc/",
    "DayType": "Both",
    "Days": "Tuesday, Saturday",
    "Times": "7:00 PM, 8:00 AM",
    "Distance": "",
    "latitude": 40.8899894,
    "longitude": -73.8980578
  },
  {
    "RunClubName": "Van Cortlandt Track Club",
    "Borough": "Bronx",
    "Address": "Van Cortlandt Park, Broadway and Van, Cortlandt Park South, Bronx, NY 10471, USA",
    "Website": "https://www.instagram.com/vancortlandttc/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 PM",
    "Distance": "Tempo",
    "latitude": 40.8971354,
    "longitude": -73.8860942
  },
  {
    "RunClubName": "Achilles International NYC",
    "Borough": "Brooklyn",
    "Address": "Garfield Pl & Prospect Park W, Brooklyn, NY 11215, USA",
    "Website": "https://www.instagram.com/achillesnyc/?hl=en",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:00 PM",
    "Distance": "",
    "latitude": 40.6700355,
    "longitude": -73.9723229
  },
  {
    "RunClubName": "Adidas Runners",
    "Borough": "Brooklyn",
    "Address": "Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA",
    "Website": "https://www.instagram.com/adidasrunners/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 AM",
    "Distance": "",
    "latitude": 40.6740248,
    "longitude": -73.9701254
  },
  {
    "RunClubName": "Bed-Stuy Run Club",
    "Borough": "Brooklyn",
    "Address": "Halsey St & Saratoga Ave, Brooklyn, NY 11233, USA",
    "Website": "https://www.instagram.com/__m.schmidt/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6855149,
    "longitude": -73.9177083
  },
  {
    "RunClubName": "Bedstuy Flyers",
    "Borough": "Brooklyn",
    "Address": "1700 Fulton St, Brooklyn, NY 11213, USA",
    "Website": "https://www.instagram.com/bedstuyflyers/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:15 AM",
    "Distance": "",
    "latitude": 40.6788731,
    "longitude": -73.9315586
  },
  {
    "RunClubName": "Bedstuy Flyers",
    "Borough": "Brooklyn",
    "Address": "570 Putnam Ave, Brooklyn, NY 11221, USA",
    "Website": "https://www.instagram.com/bedstuyflyers/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:30 AM",
    "Distance": "",
    "latitude": 40.6851952,
    "longitude": -73.9388704
  },
  {
    "RunClubName": "BK Heights Run Club",
    "Borough": "Brooklyn",
    "Address": "Dumbo, Brooklyn, NY 11201, USA",
    "Website": "https://www.instagram.com/bkhrunclub/?hl=en",
    "DayType": "Weekday",
    "Days": "Monday, Tuesday, Wednesday, Thursday, Friday",
    "Times": "7:20 AM, 7:20 AM, 7:20 AM, 7:20 AM, 7:20 AM",
    "Distance": "",
    "latitude": 40.7033164,
    "longitude": -73.9881451
  },
  {
    "RunClubName": "BK Heights Run Club",
    "Borough": "Brooklyn",
    "Address": "209 Joralemon St, Brooklyn, NY 11201, USA",
    "Website": "https://www.instagram.com/bkhrunclub/?hl=en",
    "DayType": "Both",
    "Days": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
    "Times": "6:30 PM, 6:30 PM, 6:30 PM, 6:30 PM, 6:30 PM, 8:00 AM",
    "Distance": "",
    "latitude": 40.6928442,
    "longitude": -73.990303
  },
  {
    "RunClubName": "BK Heights Run Club",
    "Borough": "Brooklyn",
    "Address": "401 Biscayne Blvd Unit M100, Miami, FL 33132, USA",
    "Website": "https://www.instagram.com/bkhrunclub/?hl=en",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "9:00 AM",
    "Distance": "",
    "latitude": 25.7780627,
    "longitude": -80.1865586
  },
  {
    "RunClubName": "BK Run Project",
    "Borough": "Brooklyn",
    "Address": "Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA",
    "Website": "https://www.bkrunproject.com/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "6:30 AM, 6:30 AM",
    "Distance": "",
    "latitude": 40.6740248,
    "longitude": -73.9701254
  },
  {
    "RunClubName": "BK Run Project",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.bkrunproject.com/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "Varies - check website",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Black Men Run",
    "Borough": "Brooklyn",
    "Address": "Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA",
    "Website": "https://www.instagram.com/blackmenrunnyc/",
    "DayType": "Both",
    "Days": "Wednesday, Saturday, Weekend",
    "Times": "7:15 PM, 8:00 AM, nan",
    "Distance": "",
    "latitude": 40.6740248,
    "longitude": -73.9701254
  },
  {
    "RunClubName": "Brooklyn Rogues",
    "Borough": "Brooklyn",
    "Address": "Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA",
    "Website": "https://www.instagram.com/brooklynrogues/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "6:00 AM, 6:00 AM",
    "Distance": "",
    "latitude": 40.6740248,
    "longitude": -73.9701254
  },
  {
    "RunClubName": "Brooklyn Rogues",
    "Borough": "Brooklyn",
    "Address": "30 Lafayette Ave, Brooklyn, NY 11217, USA",
    "Website": "https://www.instagram.com/brooklynrogues/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "7:30 AM",
    "Distance": "",
    "latitude": 40.6864737,
    "longitude": -73.9776469
  },
  {
    "RunClubName": "Brooklyn Track Club",
    "Borough": "Brooklyn",
    "Address": "769 Lorimer St, Brooklyn, NY 11222, USA",
    "Website": "https://www.brooklyntrackclub.com/training-sessions.html",
    "DayType": "Weekday",
    "Days": "Tuesday, Tuesday",
    "Times": "7:00 AM, 7:00 PM",
    "Distance": "",
    "latitude": 40.7200368,
    "longitude": -73.95172509999999
  },
  {
    "RunClubName": "Brooklyn Track Club",
    "Borough": "Brooklyn",
    "Address": "East River Park, East River Promenade, New York, NY 10002, USA",
    "Website": "https://www.brooklyntrackclub.com/training-sessions.html",
    "DayType": "Weekday",
    "Days": "Tuesday, Tuesday",
    "Times": "7:00 AM, 7:00 PM",
    "Distance": "",
    "latitude": 40.7133434,
    "longitude": -73.9757477
  },
  {
    "RunClubName": "Brooklyn Track Club",
    "Borough": "Brooklyn",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.brooklyntrackclub.com/training-sessions.html",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "nan",
    "Distance": "",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "Brooklyn Track Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.brooklyntrackclub.com/training-sessions.html",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "nan",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Brooklyn Tri Club",
    "Borough": "Brooklyn",
    "Address": "Center Dr, Brooklyn, NY, USA",
    "Website": "https://brooklyntri.org/event/run-training-with-coach-john/2022-07-27",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6606114,
    "longitude": -73.9700868
  },
  {
    "RunClubName": "Bushwick Runners",
    "Borough": "Brooklyn",
    "Address": "P33G+7F Maria Hernandez Park, Brooklyn, NY 11237, USA",
    "Website": "https://www.instagram.com/bushwickrunners/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:00 PM",
    "Distance": "",
    "latitude": 40.70318750000001,
    "longitude": -73.9238125
  },
  {
    "RunClubName": "Crown Heights Running Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.instagram.com/crownheightsrunningclub/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "6:30 AM",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Crown Heights Running Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.instagram.com/crownheightsrunningclub/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Crown Heights Running Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.instagram.com/crownheightsrunningclub/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "6:30 AM",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Crown Heights Running Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.instagram.com/crownheightsrunningclub/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Crown Heights Running Club",
    "Borough": "Brooklyn",
    "Address": "Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA",
    "Website": "https://www.instagram.com/crownheightsrunningclub/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6740248,
    "longitude": -73.9701254
  },
  {
    "RunClubName": "Crown Heights Running Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Pk, Brooklyn, NY 11225, USA",
    "Website": "https://www.instagram.com/crownheightsrunningclub/",
    "DayType": "Both",
    "Days": "Friday, Saturday",
    "Times": "6:30 AM, 8:00 AM",
    "Distance": "",
    "latitude": 40.6608764,
    "longitude": -73.9621167
  },
  {
    "RunClubName": "Dashing Whippets",
    "Borough": "Brooklyn",
    "Address": "545 President St, Brooklyn, NY 11215, USA",
    "Website": "https://www.instagram.com/dashingwhippets/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6774565,
    "longitude": -73.9847935
  },
  {
    "RunClubName": "Dashing Whippets",
    "Borough": "Brooklyn",
    "Address": "Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA",
    "Website": "https://www.instagram.com/dashingwhippets/",
    "DayType": "Both",
    "Days": "Thursday, Saturday",
    "Times": "7:00 PM, 8:30 AM",
    "Distance": "",
    "latitude": 40.6740248,
    "longitude": -73.9701254
  },
  {
    "RunClubName": "DeFine New York Run Club",
    "Borough": "Brooklyn",
    "Address": "266 Adelphi St, Brooklyn, NY 11205, USA",
    "Website": "https://www.instagram.com/definenewyorkrunclub/?hl=en",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "8:00 AM",
    "Distance": "",
    "latitude": 40.689854,
    "longitude": -73.971357
  },
  {
    "RunClubName": "Democratic Socialists of America",
    "Borough": "Brooklyn",
    "Address": "20 Grand Army Plz, Brooklyn, NY 11238, USA",
    "Website": "https://socialists.nyc/running-club/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6729962,
    "longitude": -73.96991299999999
  },
  {
    "RunClubName": "Endorphins Running Club",
    "Borough": "Brooklyn",
    "Address": "Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA",
    "Website": "https://www.instagram.com/endorphinsrunning/?hl=en",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:45 AM",
    "Distance": "",
    "latitude": 40.6740248,
    "longitude": -73.9701254
  },
  {
    "RunClubName": "Fleet Feet Running Club Brooklyn",
    "Borough": "Brooklyn",
    "Address": "151 7th Ave, Brooklyn, NY 11215, USA",
    "Website": "https://www.instagram.com/fleetfeetbrooklyn/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "9:00 AM",
    "Distance": "",
    "latitude": 40.672504,
    "longitude": -73.9766183
  },
  {
    "RunClubName": "Fort Greene Runners",
    "Borough": "Brooklyn",
    "Address": "DeKalb, IL, USA",
    "Website": "https://www.instagram.com/fortgreenerunners/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 41.9295355,
    "longitude": -88.74991279999999
  },
  {
    "RunClubName": "Fort Greene Runners",
    "Borough": "Brooklyn",
    "Address": "Hanson Pl & Fulton St, Brooklyn, NY 11217, USA",
    "Website": "https://www.instagram.com/fortgreenerunners/",
    "DayType": "Weekday",
    "Days": "Friday",
    "Times": "7:15 AM",
    "Distance": "",
    "latitude": 40.6857686,
    "longitude": -73.9730604
  },
  {
    "RunClubName": "Front Runners New York",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://frny.org/activities",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Front Runners New York",
    "Borough": "Brooklyn",
    "Address": "Brooklyn Bridge Park Pier 6, Governors Island - Atlantic Avenue/Brooklyn Bridge Park Pier 6, Brooklyn, NY 11201, USA",
    "Website": "https://frny.org/activities",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "7:00 PM, 7:00 PM",
    "Distance": "",
    "latitude": 40.6927004,
    "longitude": -74.00155099999999
  },
  {
    "RunClubName": "Girls Run NYC",
    "Borough": "Brooklyn",
    "Address": "222 Grand St, Brooklyn, NY 11211, USA",
    "Website": "https://www.instagram.com/girlsrunnyc/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:00 PM",
    "Distance": "",
    "latitude": 40.713615,
    "longitude": -73.959733
  },
  {
    "RunClubName": "Goldfinger Track Club",
    "Borough": "Brooklyn",
    "Address": "954 Putnam Ave, Brooklyn, NY 11221, USA",
    "Website": "https://www.instagram.com/gftcbklyn/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6869296,
    "longitude": -73.9239169
  },
  {
    "RunClubName": "Great Hill Track Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.instagram.com/greathilltc/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "6:30 PM, 6:30 PM",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Greenpoint Runners",
    "Borough": "Brooklyn",
    "Address": "37 Noble St, Brooklyn, NY 11222, USA",
    "Website": "https://www.instagram.com/greenpointrunners/?hl=en",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "9:00 AM",
    "Distance": "",
    "latitude": 40.7283678,
    "longitude": -73.95935829999999
  },
  {
    "RunClubName": "Kings County Fitness Club",
    "Borough": "Brooklyn",
    "Address": "Fort Greene Park, Dekalb Avenue &, S Portland Ave, Brooklyn, NY 11205, USA",
    "Website": "https://www.instagram.com/kingscountyfitnessclub/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 AM",
    "Distance": "",
    "latitude": 40.6914322,
    "longitude": -73.975246
  },
  {
    "RunClubName": "Lean Strong Fast",
    "Borough": "Brooklyn",
    "Address": "Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA",
    "Website": "https://www.instagram.com/lean.strong.fast/?hl=en",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "7:00 AM",
    "Distance": "",
    "latitude": 40.6740248,
    "longitude": -73.9701254
  },
  {
    "RunClubName": "MTHD by Oscar",
    "Borough": "Brooklyn",
    "Address": "450 Warren St, Brooklyn, NY 11217, USA",
    "Website": "https://www.instagram.com/mthdbyoscar/",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "9:00 AM",
    "Distance": "",
    "latitude": 40.6834718,
    "longitude": -73.9868838
  },
  {
    "RunClubName": "New York Flyers",
    "Borough": "Brooklyn",
    "Address": "Brooklyn, NY, USA",
    "Website": "https://www.nyflyers.org/",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "9:00 AM",
    "Distance": "",
    "latitude": 40.6736427,
    "longitude": -73.9695503
  },
  {
    "RunClubName": "Nice Jewish Runners",
    "Borough": "Brooklyn",
    "Address": "Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA",
    "Website": "https://www.instagram.com/nicejewishrunners/",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "8:30 AM",
    "Distance": "",
    "latitude": 40.6740248,
    "longitude": -73.9701254
  },
  {
    "RunClubName": "No Bad Days Run Club",
    "Borough": "Brooklyn",
    "Address": "34 River St, Savannah, GA 31401, USA",
    "Website": "https://www.instagram.com/nbd_rc",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:45 PM",
    "Distance": "",
    "latitude": 32.081661,
    "longitude": -81.0914446
  },
  {
    "RunClubName": "North Brooklyn Runners",
    "Borough": "Brooklyn",
    "Address": "McCarren Park, 776 Lorimer St, Brooklyn, NY 11222, USA",
    "Website": "https://northbrooklynrunners.org/",
    "DayType": "Both",
    "Days": "Monday, Monday, Monday, Tuesday, Tuesday, Wednesday, Wednesday, Thursday, Thursday, Saturday, Saturday, Sunday",
    "Times": "6:45 AM, 7:30 PM, 9:10 PM, 6:30 AM, 7:30 PM, 6:00 AM, 7:00 PM, 6:30 AM, 7:30 PM, 8:00 AM, 9:00 AM, 8:00 AM",
    "Distance": "",
    "latitude": 40.7210405,
    "longitude": -73.95134879999999
  },
  {
    "RunClubName": "North Brooklyn Runners",
    "Borough": "Brooklyn",
    "Address": "Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA",
    "Website": "https://northbrooklynrunners.org/",
    "DayType": "Weekday",
    "Days": "Tuesday, Wednesday, Thursday",
    "Times": "7:00 PM, 7:30 PM, 6:30 PM",
    "Distance": "",
    "latitude": 40.6740248,
    "longitude": -73.9701254
  },
  {
    "RunClubName": "North Brooklyn Runners",
    "Borough": "Brooklyn",
    "Address": "677 Kent Ave, Brooklyn, NY 11249, USA",
    "Website": "https://northbrooklynrunners.org/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "8:00 AM",
    "Distance": "",
    "latitude": 40.7007889,
    "longitude": -73.962549
  },
  {
    "RunClubName": "November Project",
    "Borough": "Brooklyn",
    "Address": "Fort Greene Park, Dekalb Avenue &, S Portland Ave, Brooklyn, NY 11205, USA",
    "Website": "https://november-project.com/brooklyn-ny/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:28 AM",
    "Distance": "",
    "latitude": 40.6914322,
    "longitude": -73.975246
  },
  {
    "RunClubName": "NYC Sprint Collective",
    "Borough": "Brooklyn",
    "Address": "McCarren Park, 776 Lorimer St, Brooklyn, NY 11222, USA",
    "Website": "https://www.instagram.com/nycsprintcollective/",
    "DayType": "Weekday",
    "Days": "Tuesday, Friday",
    "Times": "6:00 PM, 8:00 AM",
    "Distance": "",
    "latitude": 40.7210405,
    "longitude": -73.95134879999999
  },
  {
    "RunClubName": "Off the Hook Track Club",
    "Borough": "Brooklyn",
    "Address": "155 Bay St, Brooklyn, NY 11231, USA",
    "Website": "https://www.instagram.com/offthehooktc/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 AM",
    "Distance": "",
    "latitude": 40.6730613,
    "longitude": -74.0087203
  },
  {
    "RunClubName": "On Williamsburg Run Club",
    "Borough": "Brooklyn",
    "Address": "Williamsburg, Brooklyn, NY, USA",
    "Website": "https://www.eventbrite.com/e/on-williamsburg-tuesday-community-group-runs-tickets-796928252857?aff=oddtdtcreator",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.7081156,
    "longitude": -73.9570696
  },
  {
    "RunClubName": "Positive Mental Energy",
    "Borough": "Brooklyn",
    "Address": "P33G+7F Maria Hernandez Park, Brooklyn, NY 11237, USA",
    "Website": "https://www.instagram.com/positivementalenergy.nyc/",
    "DayType": "Both",
    "Days": "Tuesday, Saturday",
    "Times": "6:30 PM, 10:00 AM",
    "Distance": "",
    "latitude": 40.70318750000001,
    "longitude": -73.9238125
  },
  {
    "RunClubName": "Prospect Park Track Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.instagram.com/prospectparktc/",
    "DayType": "Both",
    "Days": "Wednesday, Sunday",
    "Times": "7:00 PM, 9:00 AM",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Prospect Park Track Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.instagram.com/prospectparktc/",
    "DayType": "Weekday",
    "Days": "Friday",
    "Times": "7:00 AM",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Prospect Park Track Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.instagram.com/prospectparktc/",
    "DayType": "Both",
    "Days": "Wednesday, Sunday",
    "Times": "7:00 PM, 9:00 AM",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Prospect Park Track Club",
    "Borough": "Brooklyn",
    "Address": "Prospect Park, Brooklyn, NY, USA",
    "Website": "https://www.instagram.com/prospectparktc/",
    "DayType": "Weekday",
    "Days": "Friday",
    "Times": "7:00 AM",
    "Distance": "",
    "latitude": 40.6602037,
    "longitude": -73.9689558
  },
  {
    "RunClubName": "Prospect Park Track Club",
    "Borough": "Brooklyn",
    "Address": "Bartel-Pritchard Square, Prospect Park Southwest, Brooklyn, NY 11215, USA",
    "Website": "https://www.instagram.com/prospectparktc/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "8:00 AM",
    "Distance": "",
    "latitude": 40.6609484,
    "longitude": -73.9798989
  },
  {
    "RunClubName": "Queers Run Brooklyn",
    "Borough": "Brooklyn",
    "Address": "10 Grand Army Plz, Brooklyn, NY 11238, USA",
    "Website": "https://www.instagram.com/queersrunbrooklyn/",
    "DayType": "Both",
    "Days": "1st & 3rd Monday, Tuesday, Thursday, Saturday, 2nd & 4th Sunday",
    "Times": "7:00 PM, 7:30 AM, 7:00 PM, 10:00 AM, 11:00 AM",
    "Distance": "",
    "latitude": 40.67251110000001,
    "longitude": -73.9682
  },
  {
    "RunClubName": "Rabbit Movers Running Club",
    "Borough": "Brooklyn",
    "Address": "Columbus Cir, New York, NY, USA",
    "Website": "https://www.instagram.com/rabbit.movers.running.club/?hl=en",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "8:00 AM",
    "Distance": "",
    "latitude": 40.767848,
    "longitude": -73.9815219
  },
  {
    "RunClubName": "Rage and Release",
    "Borough": "Brooklyn",
    "Address": "845 Dean St, Brooklyn, NY 11238, USA",
    "Website": "https://www.instagram.com/rageandrelease/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:50 PM",
    "Distance": "",
    "latitude": 40.6790198,
    "longitude": -73.961654
  },
  {
    "RunClubName": "Resident Runners",
    "Borough": "Brooklyn",
    "Address": "250 Ashland Pl, Brooklyn, NY 11217, USA",
    "Website": "https://www.instagram.com/residentrunners/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:30 AM",
    "Distance": "",
    "latitude": 40.6876846,
    "longitude": -73.9787132
  },
  {
    "RunClubName": "Ridge Runners NYC",
    "Borough": "Brooklyn",
    "Address": "78th St & 3rd Ave, Brooklyn, NY 11209, USA",
    "Website": "https://www.instagram.com/ridgerunnersnyc/ OR https://www.facebook.com/groups/ridgerunnersnyc",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "8:00 PM",
    "Distance": "",
    "latitude": 40.6293019,
    "longitude": -74.0286842
  },
  {
    "RunClubName": "Ridge Runners NYC",
    "Borough": "Brooklyn",
    "Address": "American Veterans Memorial Pier, Bay Ridge Ave, Brooklyn, NY 11209, USA",
    "Website": "https://www.instagram.com/ridgerunnersnyc/ OR https://www.facebook.com/groups/ridgerunnersnyc",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:30 PM",
    "Distance": "",
    "latitude": 40.6394128,
    "longitude": -74.0379857
  },
  {
    "RunClubName": "Ridge Runners NYC",
    "Borough": "Brooklyn",
    "Address": "8301 Shore Rd, Brooklyn, NY 11209, USA",
    "Website": "https://www.instagram.com/ridgerunnersnyc/ OR https://www.facebook.com/groups/ridgerunnersnyc",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.6269932,
    "longitude": -74.0401285
  },
  {
    "RunClubName": "Ridge Runners NYC",
    "Borough": "Brooklyn",
    "Address": "Shore Rd & 79th St, Brooklyn, NY 11209, USA",
    "Website": "https://www.instagram.com/ridgerunnersnyc/ OR https://www.facebook.com/groups/ridgerunnersnyc",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6313154,
    "longitude": -74.0388083
  },
  {
    "RunClubName": "Ridge Runners NYC",
    "Borough": "Brooklyn",
    "Address": "4th Ave & 86th St, Brooklyn, NY 11209, USA",
    "Website": "https://www.instagram.com/ridgerunnersnyc/ OR https://www.facebook.com/groups/ridgerunnersnyc",
    "DayType": "Weekend",
    "Days": "Saturday, Sunday",
    "Times": "7:00 AM, 7:00 AM",
    "Distance": "",
    "latitude": 40.6228093,
    "longitude": -74.0283419
  },
  {
    "RunClubName": "Running Souls Run Club",
    "Borough": "Brooklyn",
    "Address": "Bartel-Pritchard Square, Prospect Park Southwest, Brooklyn, NY 11215, USA",
    "Website": "https://www.instagram.com/runningsoulsrun/",
    "DayType": "Both",
    "Days": "Tuesday, Thursday, Saturday",
    "Times": "7:00 PM, 7:00 PM, 9:45 AM",
    "Distance": "",
    "latitude": 40.6609484,
    "longitude": -73.9798989
  },
  {
    "RunClubName": "South Brooklyn Running Club",
    "Borough": "Brooklyn",
    "Address": "Carroll Park, President St, Brooklyn, NY 11231, USA",
    "Website": "https://www.instagram.com/southbrooklynrc/",
    "DayType": "Both",
    "Days": "Monday, Tuesday, Wednesday, Friday, Sunday",
    "Times": "6:45 AM, 7:15 PM, 7:00 PM, 6:45 AM, 4:00 PM",
    "Distance": "",
    "latitude": 40.6810509,
    "longitude": -73.9954352
  },
  {
    "RunClubName": "South Brooklyn Running Club",
    "Borough": "Brooklyn",
    "Address": "Red Hook Ball Fields 7, 98 Lorraine St, Brooklyn, NY 11231, USA",
    "Website": "https://www.instagram.com/southbrooklynrc/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:15 AM",
    "Distance": "",
    "latitude": 40.6738304,
    "longitude": -74.00576439999999
  },
  {
    "RunClubName": "Spartan Sundays Run Club",
    "Borough": "Brooklyn",
    "Address": "600 Kingston Ave, Brooklyn, NY 11203, USA",
    "Website": "https://www.instagram.com/spartansundaysrunclub/",
    "DayType": "Weekday",
    "Days": "Monday, Wednesday",
    "Times": "6:00 AM, 6:00 AM",
    "Distance": "",
    "latitude": 40.6593652,
    "longitude": -73.9431462
  },
  {
    "RunClubName": "Spartan Sundays Run Club",
    "Borough": "Brooklyn",
    "Address": "2133 Ralph Ave, Brooklyn, NY 11234, USA",
    "Website": "https://www.instagram.com/spartansundaysrunclub/",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "8:00 AM",
    "Distance": "",
    "latitude": 40.6253745,
    "longitude": -73.9163485
  },
  {
    "RunClubName": "Team We Run Kings (Team WRK)",
    "Borough": "Brooklyn",
    "Address": "150 Nevins St, Brooklyn, NY 11217, USA",
    "Website": "https://werunkings.com/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "7:00 AM",
    "Distance": "",
    "latitude": 40.68403199999999,
    "longitude": -73.9841811
  },
  {
    "RunClubName": "Ukrainian Running Club",
    "Borough": "Brooklyn",
    "Address": "3030 Stillwell Ave, Brooklyn, NY 11224, USA",
    "Website": "https://www.ukrainianrunningclub.com/",
    "DayType": "Weekday",
    "Days": "Friday",
    "Times": "5:15 AM",
    "Distance": "",
    "latitude": 40.5744829,
    "longitude": -73.98140099999999
  },
  {
    "RunClubName": "Williamsburg Track Club",
    "Borough": "Brooklyn",
    "Address": "769 Lorimer St, Brooklyn, NY 11222, USA",
    "Website": "https://www.instagram.com/wbtc_nyc/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "6:30 PM, 7:30 PM",
    "Distance": "",
    "latitude": 40.7200368,
    "longitude": -73.95172509999999
  },
  {
    "RunClubName": "Women Make Moves",
    "Borough": "Brooklyn",
    "Address": "843 Sterling Pl, Brooklyn, NY 11216, USA",
    "Website": "https://www.instagram.com/womenmakemoves/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:10 PM",
    "Distance": "",
    "latitude": 40.6726717,
    "longitude": -73.95056629999999
  },
  {
    "RunClubName": "Achilles International NYC",
    "Borough": "Manhattan",
    "Address": "2 E 90th St, New York, NY 10128, USA",
    "Website": "https://www.instagram.com/achillesnyc/?hl=en",
    "DayType": "Both",
    "Days": "Tuesday, Saturday",
    "Times": "6:00 PM, 10:15 AM",
    "Distance": "",
    "latitude": 40.784066,
    "longitude": -73.9586941
  },
  {
    "RunClubName": "Adidas Runners",
    "Borough": "Manhattan",
    "Address": "10 Columbus Cir, New York, NY 10019, USA",
    "Website": "https://www.instagram.com/adidasrunners/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "7:00 PM, 7:00 PM",
    "Distance": "",
    "latitude": 40.7685526,
    "longitude": -73.9831866
  },
  {
    "RunClubName": "Almost Friday Run Club",
    "Borough": "Manhattan",
    "Address": "Morton St, New York, NY 10014, USA",
    "Website": "https://www.instagram.com/almostfridayrunclub/?hl=en",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 AM",
    "Distance": "",
    "latitude": 40.7309548,
    "longitude": -74.0067219
  },
  {
    "RunClubName": "Beer Run Harlem Running Club (Rosie’s Run Club)",
    "Borough": "Manhattan",
    "Address": "3604 Broadway 2nd FL, New York, NY 10031, USA",
    "Website": "https://www.instagram.com/beerrunharlem/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:00 PM",
    "Distance": "2-3M",
    "latitude": 40.8284521,
    "longitude": -73.9485715
  },
  {
    "RunClubName": "Blockhouse Run Club",
    "Borough": "Manhattan",
    "Address": "W 59th St, New York, NY 10019, USA",
    "Website": "https://link.heylo.co/7co7 ",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "9:00 AM",
    "Distance": "6M",
    "latitude": 40.7683893,
    "longitude": -73.98084159999999
  },
  {
    "RunClubName": "Bridge Runners",
    "Borough": "Manhattan",
    "Address": "176 Delancey St, New York, NY 10002, USA",
    "Website": "https://www.instagram.com/bridgerunners/?hl=en",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:30 PM",
    "Distance": "",
    "latitude": 40.71790319999999,
    "longitude": -73.9849692
  },
  {
    "RunClubName": "Bunji Running",
    "Borough": "Manhattan",
    "Address": "The Mall, New York, NY, USA",
    "Website": "https://www.bunjirunning.com/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 AM",
    "Distance": "",
    "latitude": 40.7723522,
    "longitude": -73.9715901
  },
  {
    "RunClubName": "Bunji Running",
    "Borough": "Manhattan",
    "Address": "Cat Hill ASCN 1ZZ, St Helena, Ascension and Tristan da Cunha",
    "Website": "https://www.bunjirunning.com/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:30 AM",
    "Distance": "",
    "latitude": 40.7725174,
    "longitude": -73.96663869999999
  },
  {
    "RunClubName": "Central Park Running Club",
    "Borough": "Manhattan",
    "Address": "Central Park Boat House, 72 E 72nd St, New York, NY 10021, USA",
    "Website": "https://www.instagram.com/centralparkrunning/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "6:30 AM, 6:30 AM",
    "Distance": "",
    "latitude": 40.7752428,
    "longitude": -73.9688067
  },
  {
    "RunClubName": "Central Park Track Club",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.instagram.com/centralparktc/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday, Thursday",
    "Times": "5:50 AM, 5:50 AM, 7:00 PM",
    "Distance": "",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "Dashing Whippets",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.instagram.com/dashingwhippets/",
    "DayType": "Weekday",
    "Days": "Monday, Monday, Tuesday, Thursday",
    "Times": "7:00 AM, 7:00 PM, 7:00 PM, 7:00 PM",
    "Distance": "3-5M",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "Dashing Whippets",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.instagram.com/dashingwhippets/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "Dashing Whippets",
    "Borough": "Manhattan",
    "Address": "80 W 3rd St, New York, NY 10012, USA",
    "Website": "https://www.instagram.com/dashingwhippets/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.7297225,
    "longitude": -73.998874
  },
  {
    "RunClubName": "Dashing Whippets",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.instagram.com/dashingwhippets/",
    "DayType": "Weekday",
    "Days": "Monday, Monday, Tuesday, Thursday",
    "Times": "7:00 AM, 7:00 PM, 7:00 PM, 7:00 PM",
    "Distance": "3-5M",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "Dashing Whippets",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.instagram.com/dashingwhippets/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "Dashing Whippets",
    "Borough": "Manhattan",
    "Address": "Riverbank State Park, 679 Riverside Dr, New York, NY 10031, USA",
    "Website": "https://www.instagram.com/dashingwhippets/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 AM",
    "Distance": "",
    "latitude": 40.82642360000001,
    "longitude": -73.9559555
  },
  {
    "RunClubName": "Dashing Whippets",
    "Borough": "Manhattan",
    "Address": "East River Park, East River Promenade, New York, NY 10002, USA",
    "Website": "https://www.instagram.com/dashingwhippets/",
    "DayType": "Weekday",
    "Days": "Thursday, Thursday",
    "Times": "7:00 AM, 7:00 PM",
    "Distance": "Track",
    "latitude": 40.7133434,
    "longitude": -73.9757477
  },
  {
    "RunClubName": "Dashing Whippets",
    "Borough": "Manhattan",
    "Address": "10 Columbus Cir, New York, NY 10019, USA",
    "Website": "https://www.instagram.com/dashingwhippets/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "8:00 AM",
    "Distance": "Long Run",
    "latitude": 40.7685068,
    "longitude": -73.9831349
  },
  {
    "RunClubName": "Distance Project NYC",
    "Borough": "Manhattan",
    "Address": "734 10th Ave, New York, NY 10019, USA",
    "Website": "https://www.instagram.com/distanceprojectnyc/?hl=en",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 PM",
    "Distance": "4-8M",
    "latitude": 40.7647168,
    "longitude": -73.9915618
  },
  {
    "RunClubName": "Distance Project NYC",
    "Borough": "Manhattan",
    "Address": "2 E 90th St, New York, NY 10128, USA",
    "Website": "https://www.instagram.com/distanceprojectnyc/?hl=en",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "5M",
    "latitude": 40.784066,
    "longitude": -73.9586941
  },
  {
    "RunClubName": "Dyckman Run Club",
    "Borough": "Manhattan",
    "Address": "679 Riverside Dr, New York, NY 10031, USA",
    "Website": "https://www.instagram.com/dyckmanrunclub/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "5:00 PM",
    "Distance": "Speed",
    "latitude": 40.8255182,
    "longitude": -73.9564335
  },
  {
    "RunClubName": "Dyckman Run Club",
    "Borough": "Manhattan",
    "Address": "4740 Broadway, New York, NY 10040, USA",
    "Website": "https://www.instagram.com/dyckmanrunclub/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.8650136,
    "longitude": -73.9278636
  },
  {
    "RunClubName": "Empire Tri Club",
    "Borough": "Manhattan",
    "Address": "Columbus Cir, New York, NY, USA",
    "Website": "https://empiretriclub.com/calendar-of-events/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:15 PM",
    "Distance": "",
    "latitude": 40.767848,
    "longitude": -73.9815219
  },
  {
    "RunClubName": "Endorphins Running Club",
    "Borough": "Manhattan",
    "Address": "Washington Square Park, Washington Square, New York, NY 10012, USA",
    "Website": "https://www.instagram.com/endorphinsrunning/?hl=en",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "6:45 AM",
    "Distance": "4M",
    "latitude": 40.7308838,
    "longitude": -73.997332
  },
  {
    "RunClubName": "Endorphins Running Club",
    "Borough": "Manhattan",
    "Address": "764 Doris C Freedman Pl, New York, NY 10019, USA",
    "Website": "https://www.instagram.com/endorphinsrunning/?hl=en",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 PM",
    "Distance": "4-5M",
    "latitude": 40.7648084,
    "longitude": -73.97306619999999
  },
  {
    "RunClubName": "Fleet Feet Running Club Columbus Circle",
    "Borough": "Manhattan",
    "Address": "10 Columbus Cir, New York, NY 10019, USA",
    "Website": "https://www.instagram.com/nyrunningco/",
    "DayType": "Both",
    "Days": "Wednesday, Sunday",
    "Times": "6:30 PM, 8:30 AM",
    "Distance": "",
    "latitude": 40.7685526,
    "longitude": -73.9831866
  },
  {
    "RunClubName": "Fleet Feet Running Club Upper West Side",
    "Borough": "Manhattan",
    "Address": "140 W 72nd St, New York, NY 10023, USA",
    "Website": "https://www.instagram.com/fleetfeetupperwestside/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "nan",
    "Distance": "",
    "latitude": 40.777825,
    "longitude": -73.9804043
  },
  {
    "RunClubName": "Front Runners New York",
    "Borough": "Manhattan",
    "Address": "West Dr. &, Terrace Dr, New York, NY 10024, USA",
    "Website": "https://frny.org/activities",
    "DayType": "Both",
    "Days": "Wednesday, Saturday",
    "Times": "7:00 PM, 10:00 AM",
    "Distance": "1.7 - 6 miles, 3.5M, social pace",
    "latitude": 40.7747558,
    "longitude": -73.9742918
  },
  {
    "RunClubName": "Great Hill Track Club",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.instagram.com/greathilltc/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "6:00 AM, 6:00 AM",
    "Distance": "Speed, Tempo",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "Great Hill Track Club",
    "Borough": "Manhattan",
    "Address": "140 W 72nd St, New York, NY 10023, USA",
    "Website": "https://www.instagram.com/greathilltc/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "6:20 PM, 6:20 PM",
    "Distance": "Speed, Tempo",
    "latitude": 40.777825,
    "longitude": -73.9804043
  },
  {
    "RunClubName": "Hamilton Heights Running Group",
    "Borough": "Manhattan",
    "Address": "457W W 150th St, New York, NY 10031, USA",
    "Website": "https://www.instagram.com/hhrungroup/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 PM",
    "Distance": "4M",
    "latitude": 40.8281266,
    "longitude": -73.94405259999999
  },
  {
    "RunClubName": "Harlem Run",
    "Borough": "Manhattan",
    "Address": "Marcus Garvey Park, 6316 Mt Morris Park W, New York, NY 10027, USA",
    "Website": "https://www.instagram.com/harlemrun/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "7:00 PM",
    "Distance": "3-6M",
    "latitude": 40.8044257,
    "longitude": -73.9437629
  },
  {
    "RunClubName": "Harlem Run",
    "Borough": "Manhattan",
    "Address": "306 Malcolm X Blvd, New York, NY 10027, USA",
    "Website": "https://www.instagram.com/harlemrun/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 PM",
    "Distance": "Speed",
    "latitude": 40.807913,
    "longitude": -73.9449228
  },
  {
    "RunClubName": "Henwood Hounds Racing Team",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.johnhenwood.com/hounds/",
    "DayType": "Both",
    "Days": "Friday, Sunday",
    "Times": "nan, nan",
    "Distance": "Long Run, Speed",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "Manhattan Track Club",
    "Borough": "Manhattan",
    "Address": "East River Park, East River Promenade, New York, NY 10002, USA",
    "Website": "https://www.instagram.com/manhattantrackclub/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.7133434,
    "longitude": -73.9757477
  },
  {
    "RunClubName": "Manhattan Track Club",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.instagram.com/manhattantrackclub/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 AM",
    "Distance": "",
    "latitude": 40.7797706,
    "longitude": -73.97461659999999
  },
  {
    "RunClubName": "Manhattan Track Club",
    "Borough": "Manhattan",
    "Address": "EAST 72ND ST +, Center Dr, New York, NY 10021, USA",
    "Website": "https://www.instagram.com/manhattantrackclub/",
    "DayType": "Weekday",
    "Days": "Friday",
    "Times": "7:00 AM",
    "Distance": "",
    "latitude": 40.7752246,
    "longitude": -73.9687604
  },
  {
    "RunClubName": "Midnight Runners",
    "Borough": "Manhattan",
    "Address": "Pier 45 at Hudson River Park, Hudson River Greenway, New York, NY 10014, USA",
    "Website": "https://www.midnightrunners.com/mr-cities/new-york",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "10K boot camp",
    "latitude": 40.7331485,
    "longitude": -74.01250739999999
  },
  {
    "RunClubName": "Mile HIgh Run Club",
    "Borough": "Manhattan",
    "Address": "28 E 4th St, New York, NY 10003, USA",
    "Website": "https://www.instagram.com/team_mhrc/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "nan",
    "Distance": "7:04 AM",
    "latitude": 40.7273827,
    "longitude": -73.9924454
  },
  {
    "RunClubName": "New York Flyers",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.nyflyers.org/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "6:00 AM, 6:00 AM",
    "Distance": "1 hour",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "New York Flyers",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.nyflyers.org/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "9:00 AM",
    "Distance": "1 hour",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "New York Flyers",
    "Borough": "Manhattan",
    "Address": "West Side at, Central Park S, New York, NY 10019, USA",
    "Website": "https://www.nyflyers.org/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:30 PM",
    "Distance": "5M or 3-4M run/walk",
    "latitude": 40.7682489,
    "longitude": -73.98101079999999
  },
  {
    "RunClubName": "New York Flyers",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.nyflyers.org/",
    "DayType": "Weekday",
    "Days": "Tuesday, Thursday",
    "Times": "6:00 AM, 6:00 AM",
    "Distance": "1 hour",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "New York Flyers",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.nyflyers.org/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "9:00 AM",
    "Distance": "1 hour",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "New York Harriers",
    "Borough": "Manhattan",
    "Address": "2 E 90th St, New York, NY 10128, USA",
    "Website": "https://www.instagram.com/newyorkharriers/",
    "DayType": "Weekday",
    "Days": "Wednesday, Friday",
    "Times": "6:30 AM, 6:30 AM",
    "Distance": "",
    "latitude": 40.784066,
    "longitude": -73.9586941
  },
  {
    "RunClubName": "New York Harriers",
    "Borough": "Manhattan",
    "Address": "East River Park, East River Promenade, New York, NY 10002, USA",
    "Website": "https://www.instagram.com/newyorkharriers/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "Track",
    "latitude": 40.7133434,
    "longitude": -73.9757477
  },
  {
    "RunClubName": "NewBee Running Club",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.instagram.com/newbeerunningclub/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "Varies",
    "Distance": "",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "Nice Jewish Runners",
    "Borough": "Manhattan",
    "Address": "119 W 23rd St 3rd floor, New York, NY 10011, USA",
    "Website": "https://www.instagram.com/nicejewishrunners/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "6:30 PM",
    "Distance": "4.5 miles",
    "latitude": 40.7433217,
    "longitude": -73.9933307
  },
  {
    "RunClubName": "Nice Jewish Runners",
    "Borough": "Manhattan",
    "Address": "East Dr, New York, NY 10128, USA",
    "Website": "https://www.instagram.com/nicejewishrunners/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "7:30 AM",
    "Distance": "",
    "latitude": 40.78408599999999,
    "longitude": -73.959178
  },
  {
    "RunClubName": "Nike Run Club",
    "Borough": "Manhattan",
    "Address": "156 5th Ave, New York, NY 10010, USA",
    "Website": "https://www.nike.com/experiences/series/10903",
    "DayType": "Weekday",
    "Days": "Friday",
    "Times": "8:00 AM",
    "Distance": "",
    "latitude": 40.7399068,
    "longitude": -73.99105709999999
  },
  {
    "RunClubName": "Nike Run Club",
    "Borough": "Manhattan",
    "Address": "1131 3rd Ave, New York, NY 10065, USA",
    "Website": "https://www.nike.com/experiences/series/10903",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "8:00 AM",
    "Distance": "",
    "latitude": 40.7661828,
    "longitude": -73.9627947
  },
  {
    "RunClubName": "No More Lonely Runs",
    "Borough": "Manhattan",
    "Address": "111C 11th Ave, New York, NY 10011, USA",
    "Website": "https://nomorelonelyruns.com/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "10:00 AM",
    "Distance": "6M",
    "latitude": 40.74735500000001,
    "longitude": -74.0083691
  },
  {
    "RunClubName": "Not So Serious Running Group",
    "Borough": "Manhattan",
    "Address": "New York, NY 10024, USA",
    "Website": "https://www.meetup.com/Not-So-Serious-Running-Group-NYC/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 PM",
    "Distance": "5k",
    "latitude": 40.7739528,
    "longitude": -73.97096570000001
  },
  {
    "RunClubName": "Not So Serious Running Group",
    "Borough": "Manhattan",
    "Address": "Central Park, New York, NY, USA",
    "Website": "https://www.meetup.com/Not-So-Serious-Running-Group-NYC/",
    "DayType": "Weekend",
    "Days": "Saturday, Sunday",
    "Times": "10:00 AM, 10:00 AM",
    "Distance": "2-4M",
    "latitude": 40.7825547,
    "longitude": -73.9655834
  },
  {
    "RunClubName": "November Project",
    "Borough": "Manhattan",
    "Address": "New York, NY 10024, USA",
    "Website": "https://www.instagram.com/novemberprojectnyc/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:28 AM",
    "Distance": "",
    "latitude": 40.7739528,
    "longitude": -73.97096570000001
  },
  {
    "RunClubName": "NYC Running Punks",
    "Borough": "Manhattan",
    "Address": "West Side at, Central Park S, New York, NY 10019, USA",
    "Website": "https://www.instagram.com/runningpunksnyc/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "5:30 PM",
    "Distance": "",
    "latitude": 40.7682489,
    "longitude": -73.98101079999999
  },
  {
    "RunClubName": "Old Man Run Club (OMRC)",
    "Borough": "Manhattan",
    "Address": "East River Park, East River Promenade, New York, NY 10002, USA",
    "Website": "https://www.instagram.com/oldmanrunclub/?hl=en",
    "DayType": "Weekday",
    "Days": "Varies",
    "Times": "Varies - check website",
    "Distance": "",
    "latitude": 40.7133434,
    "longitude": -73.9757477
  },
  {
    "RunClubName": "On Running NYC",
    "Borough": "Manhattan",
    "Address": "363A Lafayette St, New York, NY 10012, USA",
    "Website": "https://www.instagram.com/on_running/",
    "DayType": "Weekday",
    "Days": "nan",
    "Times": "6:00 PM",
    "Distance": "",
    "latitude": 40.727013,
    "longitude": -73.9935529
  },
  {
    "RunClubName": "Orchard Street Runners",
    "Borough": "Manhattan",
    "Address": "27 Orchard St, New York, NY 10002, USA",
    "Website": "http://orchardstreetrunners.com/Posts/tuesday-nightss/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:45 PM",
    "Distance": "5-9M",
    "latitude": 40.71548019999999,
    "longitude": -73.9916961
  },
  {
    "RunClubName": "Outsiderz Run Club",
    "Borough": "Manhattan",
    "Address": "Inwood Hill Park, Payson Ave. &, Seaman Ave, New York, NY 10034, USA",
    "Website": "https://www.instagram.com/outsiderz_run_club/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.8721829,
    "longitude": -73.924776
  },
  {
    "RunClubName": "Pacesetters Run Club",
    "Borough": "Manhattan",
    "Address": "42 W 14th St, New York, NY 10011, USA",
    "Website": "https://www.instagram.com/fleetfeetnyc/",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "9:30 AM",
    "Distance": "",
    "latitude": 40.7367292,
    "longitude": -73.9956192
  },
  {
    "RunClubName": "Paragon Sports Run Club",
    "Borough": "Manhattan",
    "Address": "867 Broadway, New York, NY 10003, USA",
    "Website": "https://www.paragonsports.com/pages/run-club",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:15 PM",
    "Distance": "",
    "latitude": 40.7377091,
    "longitude": -73.9904174
  },
  {
    "RunClubName": "Pitch & Run",
    "Borough": "Manhattan",
    "Address": "Chelsea Piers, New York, NY 10011, USA",
    "Website": "https://twitter.com/PitchandrunNYC",
    "DayType": "Weekday",
    "Days": "Monday, Friday",
    "Times": "9:15 AM, 9:15 AM",
    "Distance": "",
    "latitude": 40.7473339,
    "longitude": -74.0081797
  },
  {
    "RunClubName": "Prehab Run Club",
    "Borough": "Manhattan",
    "Address": "248 E 73rd St, New York, NY 10021, USA",
    "Website": "https://www.instagram.com/prehabrunclub/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "nan",
    "Distance": "",
    "latitude": 40.7694936,
    "longitude": -73.95838479999999
  },
  {
    "RunClubName": "Resident Runners",
    "Borough": "Manhattan",
    "Address": "185 Greenwich St Space Ll4302, New York, NY 10007, USA",
    "Website": "https://www.instagram.com/residentrunners/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.7110867,
    "longitude": -74.0122437
  },
  {
    "RunClubName": "Roosevelt Island Runners",
    "Borough": "Manhattan",
    "Address": "Eleanor's Pier, W Rd, New York, NY 10044, USA",
    "Website": "https://www.instagram.com/rooseveltislandrunners/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.7599036,
    "longitude": -73.9532108
  },
  {
    "RunClubName": "Run For Chinatown",
    "Borough": "Manhattan",
    "Address": "69 Mulberry St, New York, NY 10013, USA",
    "Website": "https://runforchinatown.org/about",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.7160423,
    "longitude": -73.9994238
  },
  {
    "RunClubName": "Russian Running",
    "Borough": "Manhattan",
    "Address": "West Side at, Central Park S, New York, NY 10019, USA",
    "Website": "https://www.instagram.com/russianrunningnyc/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.7682489,
    "longitude": -73.98101079999999
  },
  {
    "RunClubName": "Saturday Morning Run Crew",
    "Borough": "Manhattan",
    "Address": "300 W 125th St, New York, NY 10027, USA",
    "Website": "https://www.instagram.com/satmornruncrew/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "Varies - check website",
    "Distance": "Long run",
    "latitude": 40.8101454,
    "longitude": -73.9515141
  },
  {
    "RunClubName": "Social Striders Running Club",
    "Borough": "Manhattan",
    "Address": "Vesey St, New York, NY 10281, USA",
    "Website": "https://www.instagram.com/socialstridersrunningclub?igsh=MWx3OTMzdnU2ZnptcA%3D%3D&utm_source=qr",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 AM",
    "Distance": "3-4M",
    "latitude": 40.7127749,
    "longitude": -74.0166084
  },
  {
    "RunClubName": "Social Striders Running Club",
    "Borough": "Manhattan",
    "Address": "2535 Oakmont Terrace Dr, St. Louis, MO 63129, USA",
    "Website": "https://www.instagram.com/socialstridersrunningclub?igsh=MWx3OTMzdnU2ZnptcA%3D%3D&utm_source=qr",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 PM",
    "Distance": "3M",
    "latitude": 38.4598236,
    "longitude": -90.30962369999999
  },
  {
    "RunClubName": "Social Striders Running Club",
    "Borough": "Manhattan",
    "Address": "6th Ave & Central Park S, New York, NY 10019, USA",
    "Website": "https://www.instagram.com/socialstridersrunningclub?igsh=MWx3OTMzdnU2ZnptcA%3D%3D&utm_source=qr",
    "DayType": "Both",
    "Days": "Thursday, Saturday, Sunday",
    "Times": "7:00 AM, 10:00 AM, 10:00 AM",
    "Distance": "2-4M",
    "latitude": 40.7657249,
    "longitude": -73.9762178
  },
  {
    "RunClubName": "South Asian Run Club",
    "Borough": "Manhattan",
    "Address": "5th Ave, New York, NY, USA",
    "Website": "southasianrunclub@gmail.com / https://www.instagram.com/southasianrunclub/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "9:00 AM",
    "Distance": "4M",
    "latitude": 40.7744123,
    "longitude": -73.9656103
  },
  {
    "RunClubName": "Streets 101",
    "Borough": "Manhattan",
    "Address": "295 Madison Ave #1026, New York, NY 10017, USA",
    "Website": "https://www.streets101.run/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "8:00 AM",
    "Distance": "Long run",
    "latitude": 40.7517644,
    "longitude": -73.97912939999999
  },
  {
    "RunClubName": "The Most Informal Running Club Ever",
    "Borough": "Manhattan",
    "Address": "East River Park, East River Promenade, New York, NY 10002, USA",
    "Website": "https://www.instagram.com/tmircenyc/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.7133434,
    "longitude": -73.9757477
  },
  {
    "RunClubName": "The Most Informal Running Club Ever",
    "Borough": "Manhattan",
    "Address": "Union Square, New York, NY 10003, USA",
    "Website": "https://www.instagram.com/tmircenyc/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:45 PM",
    "Distance": "",
    "latitude": 40.7365576,
    "longitude": -73.9957093
  },
  {
    "RunClubName": "The Most Informal Running Club Ever",
    "Borough": "Manhattan",
    "Address": "4 Union Square E, New York, NY 10003, USA",
    "Website": "https://www.instagram.com/tmircenyc/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "9:30 AM",
    "Distance": "",
    "latitude": 40.7346935,
    "longitude": -73.9912519
  },
  {
    "RunClubName": "UES Run Club",
    "Borough": "Manhattan",
    "Address": "John Finley Walk, New York, NY, USA",
    "Website": "https://www.instagram.com/uesrunclub/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.7679217,
    "longitude": -73.9494885
  },
  {
    "RunClubName": "UES Run Club",
    "Borough": "Manhattan",
    "Address": "2 E 90th St, New York, NY 10128, USA",
    "Website": "https://www.instagram.com/uesrunclub/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "9:00 AM",
    "Distance": "",
    "latitude": 40.784066,
    "longitude": -73.9586941
  },
  {
    "RunClubName": "Ukrainian Running Club",
    "Borough": "Manhattan",
    "Address": "West Side at, Central Park S, New York, NY 10019, USA",
    "Website": "https://www.ukrainianrunningclub.com/",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "8:00 AM",
    "Distance": "",
    "latitude": 40.7682489,
    "longitude": -73.98101079999999
  },
  {
    "RunClubName": "Upper West Side Run Club",
    "Borough": "Manhattan",
    "Address": "West Dr. &, Terrace Dr, New York, NY 10024, USA",
    "Website": "https://www.instagram.com/upperwestsiderunclub/?hl=en",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:45 AM",
    "Distance": "5 miles",
    "latitude": 40.7747558,
    "longitude": -73.9742918
  },
  {
    "RunClubName": "Upper West Side Run Club",
    "Borough": "Manhattan",
    "Address": "200 Central Prk W, New York, NY 10024, USA",
    "Website": "https://www.instagram.com/upperwestsiderunclub/?hl=en",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:30 PM",
    "Distance": "3-5 miles",
    "latitude": 40.7813241,
    "longitude": -73.9739882
  },
  {
    "RunClubName": "Upper West Side Run Club",
    "Borough": "Manhattan",
    "Address": "W 72nd St, New York, NY 10023, USA",
    "Website": "https://www.instagram.com/upperwestsiderunclub/?hl=en",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "10:00 AM",
    "Distance": "4-5M",
    "latitude": 40.780642,
    "longitude": -73.98579699999999
  },
  {
    "RunClubName": "We Are NYC Running Club",
    "Borough": "Manhattan",
    "Address": "East River Park, East River Promenade, New York, NY 10002, USA",
    "Website": "https://www.instagram.com/wearenycrc/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:00 PM",
    "Distance": "Track",
    "latitude": 40.7133434,
    "longitude": -73.9757477
  },
  {
    "RunClubName": "We Are NYC Running Club",
    "Borough": "Manhattan",
    "Address": "2 E 90th St, New York, NY 10128, USA",
    "Website": "https://www.instagram.com/wearenycrc/",
    "DayType": "Weekend",
    "Days": "Saturday, Saturday",
    "Times": "7:00 AM, 8:00 AM",
    "Distance": "\"Longer\" Long Run, \"Shorter\" Long Run",
    "latitude": 40.784066,
    "longitude": -73.9586941
  },
  {
    "RunClubName": "We Run Uptown (WRU)",
    "Borough": "Manhattan",
    "Address": "4463 Broadway, New York, NY 10040, USA",
    "Website": "https://www.instagram.com/wrucrew/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "7:15 PM",
    "Distance": "",
    "latitude": 40.85734799999999,
    "longitude": -73.9325554
  },
  {
    "RunClubName": "We Run Uptown (WRU)",
    "Borough": "Manhattan",
    "Address": "5008 Broadway, New York, NY 10034, USA",
    "Website": "https://www.instagram.com/wrucrew/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.8687133,
    "longitude": -73.9174737
  },
  {
    "RunClubName": "West Side YMCA Road Runners Club",
    "Borough": "Manhattan",
    "Address": "5 W 63rd St., New York, NY 10023, USA",
    "Website": "https://www.strava.com/clubs/west-side-ymca-road-runners-club-221421",
    "DayType": "Weekday",
    "Days": "Monday, Wednesday",
    "Times": "6:30 PM, 6:30 PM",
    "Distance": "",
    "latitude": 40.7708731,
    "longitude": -73.9805895
  },
  {
    "RunClubName": "Achilles International NYC",
    "Borough": "Queens",
    "Address": "47-01 111th St, Corona, NY 11368, USA",
    "Website": "https://www.instagram.com/achillesnyc/?hl=en",
    "DayType": "Weekend",
    "Days": "Sunday",
    "Times": "9:00 AM",
    "Distance": "",
    "latitude": 40.7472583,
    "longitude": -73.8516925
  },
  {
    "RunClubName": "Alley Pond Striders",
    "Borough": "Queens",
    "Address": "Winchester Blvd, California, USA",
    "Website": "https://www.alleypondstriders.com/",
    "DayType": "Weekend",
    "Days": "Saturday, Sunday",
    "Times": "9:00 AM, 9:00 AM",
    "Distance": "",
    "latitude": 37.2918923,
    "longitude": -121.9498909
  },
  {
    "RunClubName": "Astoria Mom Running Club (AMRC)",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/astoriamomrc/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "Varies - check website",
    "Distance": "",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Forest Park Runners",
    "Borough": "Queens",
    "Address": "Victory Field, Woodhaven, NY 11421, USA",
    "Website": "https://forestparkrunners.org/cs/forestparkrunners/page.detail?page_id=1",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "Speed",
    "latitude": 40.7022097,
    "longitude": -73.8547222
  },
  {
    "RunClubName": "Forest Park Runners",
    "Borough": "Queens",
    "Address": "Forest Park Dr & Woodhaven Blvd, Queens, NY 11421, USA",
    "Website": "https://forestparkrunners.org/cs/forestparkrunners/page.detail?page_id=1",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "8:05 AM",
    "Distance": "",
    "latitude": 40.7006539,
    "longitude": -73.8544794
  },
  {
    "RunClubName": "Great Hill Track Club",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/greathilltc/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 PM",
    "Distance": "Speed/Tempo Alternate Weeks",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Hellgate Road Runners",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/hellgaterr/",
    "DayType": "Weekday",
    "Days": "Monday, Monday",
    "Times": "6:15 AM, 7:30 PM",
    "Distance": "Hills",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Hellgate Road Runners",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/hellgaterr/",
    "DayType": "Weekday",
    "Days": "Wednesday, Wednesday",
    "Times": "6:00 AM, 7:30 PM",
    "Distance": "Speed",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Hellgate Road Runners",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/hellgaterr/",
    "DayType": "Both",
    "Days": "Thursday, Saturday, Saturday",
    "Times": "7:30 PM, 8:40 AM, 9:00 AM",
    "Distance": "10K, Long Run, Speed",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Hellgate Road Runners",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/hellgaterr/",
    "DayType": "Weekday",
    "Days": "Monday, Monday",
    "Times": "6:15 AM, 7:30 PM",
    "Distance": "Hills",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Hellgate Road Runners",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/hellgaterr/",
    "DayType": "Weekday",
    "Days": "Wednesday, Wednesday",
    "Times": "6:00 AM, 7:30 PM",
    "Distance": "Speed",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Hellgate Road Runners",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/hellgaterr/",
    "DayType": "Both",
    "Days": "Thursday, Saturday, Saturday",
    "Times": "7:30 PM, 8:40 AM, 9:00 AM",
    "Distance": "10K, Long Run, Speed",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Hellgate Road Runners",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/hellgaterr/",
    "DayType": "Weekday",
    "Days": "Monday, Monday",
    "Times": "6:15 AM, 7:30 PM",
    "Distance": "Hills",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Hellgate Road Runners",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/hellgaterr/",
    "DayType": "Weekday",
    "Days": "Wednesday, Wednesday",
    "Times": "6:00 AM, 7:30 PM",
    "Distance": "Speed",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Hellgate Road Runners",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/hellgaterr/",
    "DayType": "Both",
    "Days": "Thursday, Saturday, Saturday",
    "Times": "7:30 PM, 8:40 AM, 9:00 AM",
    "Distance": "10K, Long Run, Speed",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Lone Wolf Track Club",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/lonewolftc/?hl=en",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 PM",
    "Distance": "Speed",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Long Island City Runners (LIC Runners)",
    "Borough": "Queens",
    "Address": "32-23 Queens Blvd, Long Island City, NY 11101, USA",
    "Website": "https://www.instagram.com/licrunners/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "7:00 PM",
    "Distance": "Track",
    "latitude": 40.745115,
    "longitude": -73.9322241
  },
  {
    "RunClubName": "Long Island City Runners (LIC Runners)",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/licrunners/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "Track",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Queens Distance Runners",
    "Borough": "Queens",
    "Address": "80-02 Northern Blvd, Jackson Heights, NY 11372, USA",
    "Website": "https://www.instagram.com/queensdistance/",
    "DayType": "Weekday",
    "Days": "Monday, Wednesday",
    "Times": "6:00 PM, 6:30 PM",
    "Distance": "",
    "latitude": 40.7552503,
    "longitude": -73.8870804
  },
  {
    "RunClubName": "Queens Distance Runners",
    "Borough": "Queens",
    "Address": "87-48 78th St, Woodhaven, NY 11421, USA",
    "Website": "https://www.instagram.com/queensdistance/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.6898112,
    "longitude": -73.8635147
  },
  {
    "RunClubName": "Queens Distance Runners",
    "Borough": "Queens",
    "Address": "33-15 Ditmars Blvd, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/queensdistance/",
    "DayType": "Weekday",
    "Days": "Monday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.7751808,
    "longitude": -73.9089998
  },
  {
    "RunClubName": "Queens Distance Runners",
    "Borough": "Queens",
    "Address": "102nd St & 63rd Dr, Queens, NY 11374, USA",
    "Website": "https://www.instagram.com/queensdistance/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.7324332,
    "longitude": -73.8539074
  },
  {
    "RunClubName": "Queens Distance Runners",
    "Borough": "Queens",
    "Address": "Victory Field, Woodhaven, NY 11421, USA",
    "Website": "https://www.instagram.com/queensdistance/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 AM",
    "Distance": "Track",
    "latitude": 40.7022097,
    "longitude": -73.8547222
  },
  {
    "RunClubName": "Queens Distance Runners",
    "Borough": "Queens",
    "Address": "8000 Utopia Pkwy, Jamaica, NY 11439, USA",
    "Website": "https://www.instagram.com/queensdistance/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 PM",
    "Distance": "Track",
    "latitude": 40.7218122,
    "longitude": -73.7951149
  },
  {
    "RunClubName": "Queens Distance Runners",
    "Borough": "Queens",
    "Address": "3202 Francis Lewis Blvd, Flushing, NY 11358, USA",
    "Website": "https://www.instagram.com/queensdistance/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.7686939,
    "longitude": -73.7920711
  },
  {
    "RunClubName": "Queens Distance Runners",
    "Borough": "Queens",
    "Address": "264-21 Union Tpke, Glen Oaks, NY 11004, USA",
    "Website": "https://www.instagram.com/queensdistance/",
    "DayType": "Weekday",
    "Days": "Friday",
    "Times": "6:00 AM",
    "Distance": "",
    "latitude": 40.7492125,
    "longitude": -73.7082147
  },
  {
    "RunClubName": "Queens Distance Runners",
    "Borough": "Queens",
    "Address": "108-12 72nd Ave, Forest Hills, NY 11375, USA",
    "Website": "https://www.instagram.com/queensdistance/",
    "DayType": "Weekday",
    "Days": "Friday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.71962449999999,
    "longitude": -73.842215
  },
  {
    "RunClubName": "Queens Don't Nok the Run",
    "Borough": "Queens",
    "Address": "6501 Kissena Blvd # 3, Kew Gardens Hills, NY 11367, USA",
    "Website": "https://www.instagram.com/qns_dontnoktherun/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:45 PM",
    "Distance": "",
    "latitude": 40.73702,
    "longitude": -73.8144107
  },
  {
    "RunClubName": "Queens Rebels Run Club",
    "Borough": "Queens",
    "Address": "33-15 Ditmars Blvd, Astoria, NY 11105, USA",
    "Website": "https://www.instagram.com/qrrc718/?hl=en",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.7751808,
    "longitude": -73.9089998
  },
  {
    "RunClubName": "Run Hustle Run",
    "Borough": "Queens",
    "Address": "135-22 Hillside Ave., Richmond Hill, NY 11418, USA",
    "Website": "https://www.instagram.com/runhustlerun/",
    "DayType": "Both",
    "Days": "Tuesday, Sunday",
    "Times": "7:00 PM, 6:45 AM",
    "Distance": "Long Run",
    "latitude": 40.703746,
    "longitude": -73.818632
  },
  {
    "RunClubName": "Run Hustle Run",
    "Borough": "Queens",
    "Address": "Victory Field, Woodhaven, NY 11421, USA",
    "Website": "https://www.instagram.com/runhustlerun/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:00 AM",
    "Distance": "Track",
    "latitude": 40.7022097,
    "longitude": -73.8547222
  },
  {
    "RunClubName": "Run LIC",
    "Borough": "Queens",
    "Address": "21-03 45th Rd, Long Island City, NY 11101, USA",
    "Website": "https://www.meetup.com/LongIslandCity-Runners/",
    "DayType": "Weekday",
    "Days": "Monday, Thursday",
    "Times": "7:00 AM, 6:30 PM",
    "Distance": "4M, Speed",
    "latitude": 40.7467323,
    "longitude": -73.94760389999999
  },
  {
    "RunClubName": "Run LIC",
    "Borough": "Queens",
    "Address": "Long Island City, Center Blvd &, 46th Ave, New York, NY 10044, USA",
    "Website": "https://www.meetup.com/LongIslandCity-Runners/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 PM",
    "Distance": "3M",
    "latitude": 40.7484086,
    "longitude": -73.9577202
  },
  {
    "RunClubName": "Run LIC",
    "Borough": "Queens",
    "Address": "45th Rd, Queens, NY 11101, USA",
    "Website": "https://www.meetup.com/LongIslandCity-Runners/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "7:00 AM",
    "Distance": "Long Run 4-6M",
    "latitude": 40.7469346,
    "longitude": -73.9491757
  },
  {
    "RunClubName": "Team WEPA",
    "Borough": "Queens",
    "Address": "113-30 Queens Blvd, Forest Hills, NY 11375, USA",
    "Website": "https://www.instagram.com/team_wepa_nyc/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "6:45 PM",
    "Distance": "",
    "latitude": 40.7170196,
    "longitude": -73.83545869999999
  },
  {
    "RunClubName": "We Run Hollis",
    "Borough": "Queens",
    "Address": "211-04 Hollis Ave, Queens Village, NY 11429, USA",
    "Website": "https://www.instagram.com/werunhollis/",
    "DayType": "Weekend",
    "Days": "Saturday",
    "Times": "9:00 AM",
    "Distance": "",
    "latitude": 40.7087985,
    "longitude": -73.7463025
  },
  {
    "RunClubName": "Wolf Runners of Queens",
    "Borough": "Queens",
    "Address": "34th Ave & Junction Blvd, Queens, NY 11372, USA",
    "Website": "https://www.instagram.com/wolf.runners.of_queens/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 PM",
    "Distance": "",
    "latitude": 40.7549927,
    "longitude": -73.8726753
  },
  {
    "RunClubName": "Woodside-Sunnyside Runners",
    "Borough": "Queens",
    "Address": "54th St & Woodside Ave, Queens, NY 11377, USA",
    "Website": "https://www.meetup.com/Woodside-Sunnyside-Runners/?_cookie-check=_rB-Q70x-pvBinUq",
    "DayType": "Both",
    "Days": "Tuesday, Saturday",
    "Times": "7:00 PM, 8:30 AM",
    "Distance": "3.5M",
    "latitude": 40.7474037,
    "longitude": -73.9095597
  },
  {
    "RunClubName": "Woodside-Sunnyside Runners",
    "Borough": "Queens",
    "Address": "Astoria Park, 19 19th St, Astoria, NY 11105, USA",
    "Website": "https://www.meetup.com/Woodside-Sunnyside-Runners/?_cookie-check=_rB-Q70x-pvBinUq",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "7:00 PM",
    "Distance": "Track",
    "latitude": 40.7785364,
    "longitude": -73.92283359999999
  },
  {
    "RunClubName": "Woodside-Sunnyside Runners",
    "Borough": "Queens",
    "Address": "43rd St & Skillman Ave, Queens, NY 11101, USA",
    "Website": "https://www.meetup.com/Woodside-Sunnyside-Runners/?_cookie-check=_rB-Q70x-pvBinUq",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 PM",
    "Distance": "6M",
    "latitude": 40.7468996,
    "longitude": -73.9208014
  },
  {
    "RunClubName": "World's Fair Run Crew (WFRC)",
    "Borough": "Queens",
    "Address": "135-18 Northern Blvd, Flushing, NY 11354, USA",
    "Website": "https://www.instagram.com/worldsfairruncrew/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:45 PM",
    "Distance": "",
    "latitude": 40.7626517,
    "longitude": -73.8325657
  },
  {
    "RunClubName": "Richmond Rockets",
    "Borough": "Staten Island",
    "Address": "Clove Lakes Park, 1150 Clove Rd, Staten Island, NY 10301, USA",
    "Website": "https://www.therichmondrockets.com/",
    "DayType": "Weekday",
    "Days": "Thursday",
    "Times": "7:00 PM",
    "Distance": "",
    "latitude": 40.6186608,
    "longitude": -74.11163979999999
  },
  {
    "RunClubName": "Staten Island Athletic Club",
    "Borough": "Staten Island",
    "Address": "Clove Lakes Park, 1150 Clove Rd, Staten Island, NY 10301, USA",
    "Website": "https://www.instagram.com/staten_island_athletic_club/",
    "DayType": "Both",
    "Days": "Monday, Tuesday, Saturday",
    "Times": "6:15 PM, 6:15 PM, 9:00 AM",
    "Distance": "3M",
    "latitude": 40.6186608,
    "longitude": -74.11163979999999
  },
  {
    "RunClubName": "Staten Island Athletic Club",
    "Borough": "Staten Island",
    "Address": "Silver Lake Park, 9006 Silver Lake Rd, Maple Falls, WA 98266, USA",
    "Website": "https://www.instagram.com/staten_island_athletic_club/",
    "DayType": "Weekday",
    "Days": "Tuesday",
    "Times": "6:30 AM",
    "Distance": "Speed",
    "latitude": 48.9715717,
    "longitude": -122.0691689
  },
  {
    "RunClubName": "Staten Island Athletic Club",
    "Borough": "Staten Island",
    "Address": "Greenbelt Nature Center, 700 Rockland Ave, Staten Island, NY 10314, USA",
    "Website": "https://www.instagram.com/staten_island_athletic_club/",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:30 PM",
    "Distance": "Trail Run",
    "latitude": 40.5884511,
    "longitude": -74.13916669999999
  },
  {
    "RunClubName": "Yonkers Running Project aka YRP",
    "Borough": "Yonkers",
    "Address": "100 Main St, Yonkers, NY 10701, USA",
    "Website": "https://www.instagram.com/yonkersrunningproject/?hl=en",
    "DayType": "Weekday",
    "Days": "Wednesday",
    "Times": "6:45 PM",
    "Distance": "5K",
    "latitude": 40.9349187,
    "longitude": -73.90413269999999
  }
];
